<?php
namespace App\Logger\Formatter;

/**
 * Class Colors
 * @package App\Logger
 */
class Colors
{
    /**
     * Foreground Colors
     */
    const CONSOLE_FOREGROUND_COLOR_BLACK = '0;30';
    const CONSOLE_FOREGROUND_COLOR_Blue = '0;34';
    const CONSOLE_FOREGROUND_COLOR_Green = '0;32';
    const CONSOLE_FOREGROUND_COLOR_CYAN = '0;36';
    const CONSOLE_FOREGROUND_COLOR_RED = '0;31';
    const CONSOLE_FOREGROUND_COLOR_PURPLE = '0;35';
    const CONSOLE_FOREGROUND_COLOR_BROWN = '0;33';
    const CONSOLE_FOREGROUND_COLOR_LIGHT_GRAY = '0;37';
    const CONSOLE_FOREGROUND_COLOR_DARK_GREY = '1;30';
    const CONSOLE_FOREGROUND_COLOR_LIGHT_BLUE = '1;34';
    const CONSOLE_FOREGROUND_COLOR_LIGHT_GREEN = '1;32';
    const CONSOLE_FOREGROUND_COLOR_LIGHT_CYAN = '1;36';
    const CONSOLE_FOREGROUND_COLOR_LIGHT_RED = '1;31';
    const CONSOLE_FOREGROUND_COLOR_LIGHT_PURPLE = '1;35';
    const CONSOLE_FOREGROUND_COLOR_YELLOW = '1;33';
    const CONSOLE_FOREGROUND_COLOR_WHITE = '1;37';

    /**
     * Background Colors
     */
    const CONSOLE_BACKGROUND_COLOR_BLACK = '40';
    const CONSOLE_BACKGROUND_COLOR_RED = '41';
    const CONSOLE_BACKGROUND_COLOR_GREEN = '42';
    const CONSOLE_BACKGROUND_COLOR_YELLOW = '43';
    const CONSOLE_BACKGROUND_COLOR_BLUE = '44';
    const CONSOLE_BACKGROUND_COLOR_MAGENTA = '45';
    const CONSOLE_BACKGROUND_COLOR_CYAN = '46';
    const CONSOLE_BACKGROUND_COLOR_LIGHT_GRAY = '47';
}
